version: 2.0.{build}
image: Visual Studio 2017

platform:
    - All

configuration:
    - Release

install:
    - npm install -g vsce

build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - ps: >-
        function SetPackageVersion($dir)
        {
            $file      = "$dir\package.json"
            $a         = Get-Content $file -raw | ConvertFrom-Json
            $a.version = $env:appveyor_build_version
            $a | ConvertTo-Json -Depth 20 | set-content $file
        }

        if ($true)
        {
            SetPackageVersion 'codealignment-common' 
            SetPackageVersion 'codealignment-vscode' 
        }
    - cd codealignment-common
    - npm install
    - npm run compile
    - cd ../codealignment-vscode
    - npm install
    - vsce package

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - cd codealignment-vscode
    - ps: Push-AppveyorArtifact "codealignment-vscode-$env:appveyor_build_version.vsix"
    
on_failure:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - cd codealignment-vscode
    - ps: Push-AppveyorArtifact "*.log"

deploy:
    provider: GitHub
    auth_token:
        secure: TA1/2G21wUBPSWRbmBul7xGvE3YpX8n8AEooMuwkiqhxGhD2bLJ0Y//rS7+qwIN1
    draft: true
    prerelease: false
    force_update: true
    on:
        branch: master
        appveyor_repo_tag: true
